language: php
dist: trusty

matrix:
  fast_finish: true
  include:
    - php: "7.1"
    - php: "7.2"
    - php: "7.3"
    - php: "7.4"
    - php: "8.0"
    - php: "nightly"
    - php: "master"
  allow_failures:
    - php: "8.0"
    - php: "nightly"
    - php: "master"

install:
    - composer update

script:
  - vendor/bin/phpunit
  - vendor/bin/psalm
